export const dynamic = 'force-dynamic';

/**
 * Custom /sitemap.xml route.
 *
 * NOTE (2026-09): per the site owner's explicit instruction, this route now
 * serves the exact static sitemap generated by marketing via
 * xml-sitemaps.com ("sitemap 2.xml"), unmodified — replacing the previous
 * version below, which dynamically pulled every individual product page
 * live from the database.
 *
 * Tradeoff, flagged to the site owner before this change and kept here for
 * whoever edits this next: this static list has only 10 URLs and does NOT
 * include any individual product page. It also will not update
 * automatically — the <lastmod> dates are frozen at whenever marketing
 * generated the file, and new/changed/removed products will never be
 * reflected here unless someone manually edits this file again. If
 * product-page discoverability in search results ever regresses, this is
 * the first place to look.
 *
 * Previous implementation (dynamic, included every product page) is
 * preserved in git history in case this needs to be reverted.
 */

export async function GET() {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="https://www.xml-sitemaps.com/css/sitemap.css"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">

  <url>
       <loc>https://famersfactory.com/</loc>
       <lastmod>2026-08-18T10:55:43+00:00</lastmod>
       <changefreq>daily</changefreq>
       <priority>1.0000</priority>
  </url>
  <url>
       <loc>https://famersfactory.com/llms.txt</loc>
       <lastmod>2026-08-13T13:13:06+00:00</lastmod>
       <changefreq>daily</changefreq>
       <priority>0.8000</priority>
  </url>
  <url>
       <loc>https://famersfactory.com/vegetables</loc>
       <lastmod>2026-08-18T10:55:43+00:00</lastmod>
       <changefreq>daily</changefreq>
       <priority>0.8000</priority>
  </url>
  <url>
       <loc>https://famersfactory.com/fruits</loc>
       <lastmod>2026-08-18T10:55:43+00:00</lastmod>
       <changefreq>daily</changefreq>
       <priority>0.8000</priority>
  </url>
  <url>
       <loc>https://famersfactory.com/products</loc>
       <lastmod>2026-08-18T10:55:43+00:00</lastmod>
       <changefreq>daily</changefreq>
       <priority>0.8000</priority>
  </url>
  <url>
       <loc>https://famersfactory.com/streams</loc>
       <lastmod>2026-08-18T10:55:43+00:00</lastmod>
       <changefreq>daily</changefreq>
       <priority>0.8000</priority>
  </url>
  <url>
       <loc>https://famersfactory.com/about</loc>
       <lastmod>2026-08-18T10:55:43+00:00</lastmod>
       <changefreq>daily</changefreq>
       <priority>0.8000</priority>
  </url>
  <url>
       <loc>https://famersfactory.com/contact</loc>
       <lastmod>2026-08-18T10:55:43+00:00</lastmod>
       <changefreq>daily</changefreq>
       <priority>0.8000</priority>
  </url>
  <url>
       <loc>https://famersfactory.com/privacy</loc>
       <lastmod>2026-08-18T10:55:43+00:00</lastmod>
       <changefreq>daily</changefreq>
       <priority>0.8000</priority>
  </url>
  <url>
       <loc>https://famersfactory.com/terms</loc>
       <lastmod>2026-08-18T10:55:43+00:00</lastmod>
       <changefreq>daily</changefreq>
       <priority>0.8000</priority>
  </url>
</urlset>
`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  });
}
